### ISSUE TITLE
Exception Issue

### ISSUE THREAD

**Issue by basarTHEwarrior** [rootCBR/DisruptManager#6]
Hello There anyone and everyone who can help me 

Whenever i try to install some mods and enjoy a better version of the game Watch Dogs Legion. Thanks again rootCBR Btw for all the hard work. 

This pops up and makes me unable to play the game with the mods. Please respond i am 2 days in and going crazy
![image_2023-11-15_214115423](https://github.com/rootCBR/DisruptManager/assets/150961802/169662e0-9658-4a52-9065-ec770b4810b1)

**Comment by basarTHEwarrior** [comment]
[15/11/2023 21:47:01] System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.IO.Path.Combine(String path1, String path2)
   at DisruptManager.Model.Jobs.GenericJob..ctor(Profile profile)
   at DisruptManager.Model.Jobs.GenericJob.FromProfile(Profile profile)
   at DisruptManager.ViewModel.MainViewModel.InstallMods()
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DisruptManager.App.Main()

**Comment by rootCBR** [comment]
Try moving your mods/the application to another directory, there seem to be some special characters in the mod file path.

**Comment by basarTHEwarrior** [comment]
Ahh Different Language keyboard got me again. Thanks Root it's working now

**Comment by tarnishedXsoul** [comment]
@basarTHEwarrior So how did you end up solving this ?

**Comment by tarnishedXsoul** [comment]
@basarTHEwarrior @rootCBR 
https://github.com/rootCBR/DisruptManager/issues/10#issuecomment-3411504156 this should help
